// Design tokens come from the Sebell Design System. The fragment at
// src/constants/ds-theme.cjs is generated by the DS (npm run tokens:build
// there) and copied in via `npm run sync-ds-tokens` – never hand-edit it.
// It provides colors, spacing, borderRadius, fontSize, lineHeight,
// fontWeight and fontFamily for the Prep+Eat brand (light appearance; dark
// deferred for v1).
const ds = require('./src/constants/ds-theme.cjs');

/** @type {import('tailwindcss').Config} */
module.exports = {
  // Absolute glob for the same reason as metro.config.js: release bundling
  // runs from ios/, and a cwd-relative glob would scan nothing.
  content: [require('path').join(__dirname, 'src/**/*.{ts,tsx}')],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      ...ds,
    },
  },
  plugins: [],
};
