// ──────────────────────────────────────────────
// prep-eat-theme.cjs — NativeWind / Tailwind theme fragment
// Auto-generated by @ds/tokens — do not edit.
// Source: prep-eat × default (light appearance). Run `npm run tokens:build`.
// Consume: spread into tailwind.config.js → theme.extend.
// ──────────────────────────────────────────────
module.exports = {
  "colors": {
    "surface": {
      "primary": {
        "lighter": "#EFFCE9",
        "light": "#A3ED7E",
        "main": "#5AD21E",
        "dark": "#3B8A14",
        "darker": "#2C670F",
        "DEFAULT": "#5AD21E"
      },
      "secondary": {
        "lighter": "#9E8561",
        "light": "#8E7757",
        "main": "#7E6A4E",
        "dark": "#6F5D44",
        "darker": "#5F503A",
        "DEFAULT": "#7E6A4E"
      },
      "neutral": {
        "white": "#FFFFFF",
        "lighter": "#F8F7F7",
        "light": "#E7E6E4",
        "main": "#D6D4D1",
        "dark": "#C5C2BE",
        "darker": "#B5B1AB",
        "DEFAULT": "#D6D4D1"
      }
    },
    "error": {
      "lighter": "#FDEAE7",
      "light": "#F48776",
      "main": "#DE2D12",
      "dark": "#B8250F",
      "darker": "#6D1609",
      "contrast-text": "#FFFFFF",
      "DEFAULT": "#DE2D12"
    },
    "warning": {
      "lighter": "#FEF8E7",
      "light": "#FAE299",
      "main": "#F6CB4C",
      "dark": "#F4C025",
      "darker": "#E4AE0C",
      "contrast-text": "#4F4230",
      "DEFAULT": "#F6CB4C"
    },
    "success": {
      "lighter": "#EFFCE9",
      "light": "#BCF2A1",
      "main": "#89E75A",
      "dark": "#5AD21E",
      "darker": "#3B8A14",
      "contrast-text": "#4F4230",
      "DEFAULT": "#89E75A"
    },
    "info": {
      "lighter": "#E5F2FF",
      "light": "#94C9FF",
      "main": "#42A1FF",
      "dark": "#0078F0",
      "darker": "#004F9E",
      "contrast-text": "#4F4230",
      "DEFAULT": "#42A1FF"
    },
    "text": {
      "default": "#4F4230",
      "subtle": "#5F503A",
      "disabled": "#C5C2BE",
      "link": "#5AD21E",
      "brand": "#5AD21E",
      "accent": "#7E6A4E",
      "inverse": "#FFFFFF",
      "danger": "#DE2D12",
      "success": "#5AD21E",
      "warning": "#F4C025",
      "info": "#0078F0",
      "DEFAULT": "#4F4230"
    },
    "border": {
      "default": "#C5C2BE",
      "DEFAULT": "#C5C2BE"
    },
    "icon": {
      "default": "#4F4230",
      "DEFAULT": "#4F4230"
    }
  },
  "spacing": {
    "layout-xxsmall": "4px",
    "layout-xsmall": "8px",
    "layout-small": "16px",
    "layout-medium": "24px",
    "layout-large": "40px",
    "layout-xlarge": "64px",
    "layout-xxlarge": "104px",
    "comp-xxsmall": "2px",
    "comp-xsmall": "4px",
    "comp-small": "8px",
    "comp-medium": "12px",
    "comp-large": "16px",
    "comp-xlarge": "24px",
    "comp-xxlarge": "32px"
  },
  "borderRadius": {
    "none": "0px",
    "xsmall": "4px",
    "small": "8px",
    "medium": "12px",
    "large": "16px",
    "xlarge": "24px"
  },
  "fontSize": {
    "display-1": "72px",
    "display-2": "56px",
    "display-3": "44px",
    "display-4": "32px",
    "display-5": "24px",
    "display-6": "16px",
    "paragraph": "16px",
    "small": "12px",
    "components-label": "14px",
    "components-table-header": "16px",
    "components-button-label": "16px"
  },
  "lineHeight": {
    "xxlarge": "88px",
    "xlarge": "72px",
    "large": "56px",
    "medium": "40px",
    "small": "32px",
    "xsmall": "24px",
    "xxsmall": "16px"
  },
  "fontWeight": {
    "emphasized": "700",
    "default": "400",
    "understate": "200"
  },
  "fontFamily": {
    "header": [
      "Montserrat"
    ],
    "paragraph": [
      "Montserrat"
    ]
  }
};
