#!/usr/bin/env bash
#
# Installs the backup job.  Run: npm run backup:install
#
# One job, not two: the backup script decides for itself whether a backup is
# due and carries its own "have the backups stopped?" warning.
#
# Why a runtime copy rather than pointing launchd at the repo: ~/Documents is a
# macOS privacy-protected folder and a launchd job cannot read from it. The
# first scheduled run died with "Operation not permitted" even though the same
# script worked by hand. The repo stays the source of truth - re-run this after
# editing scripts/backup-supabase.sh, or the job keeps the old version.

set -euo pipefail

LABEL="dk.sebell.prepeat.backup"
RUNTIME="$HOME/Library/Application Support/Prepeat"
AGENTS="$HOME/Library/LaunchAgents"
PLIST="$AGENTS/$LABEL.plist"
SRC="$(cd "$(dirname "$0")" && pwd)/backup-supabase.sh"

LOGFILE="$HOME/Library/Logs/prepeat-backup.log"

[ -f "$SRC" ] || { echo "cannot find $SRC" >&2; exit 1; }

echo "installing runtime copy -> $RUNTIME"
mkdir -p "$RUNTIME" "$AGENTS" "$(dirname "$LOGFILE")"
cp "$SRC" "$RUNTIME/backup-supabase.sh"
chmod 700 "$RUNTIME/backup-supabase.sh"

# Tidy away the old two-job arrangement if it is still installed.
if launchctl print "gui/$(id -u)/$LABEL-check" >/dev/null 2>&1; then
  echo "removing the old separate freshness job"
  launchctl bootout "gui/$(id -u)/$LABEL-check" 2>/dev/null || true
fi
rm -f "$AGENTS/$LABEL-check.plist" "$RUNTIME/check-backup-freshness.sh"

echo "writing $PLIST"
cat > "$PLIST" <<PLIST_END
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- GENERATED by scripts/install-backup-job.sh - do not edit by hand. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$RUNTIME/backup-supabase.sh</string>
    </array>

    <key>WorkingDirectory</key>
    <string>$RUNTIME</string>

    <!-- Only psql and curl are needed; nothing from the repo, and no node. -->
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>

    <!-- No fixed hour. At login, then every 6 hours while the Mac is on; the
         script itself does nothing unless the newest backup is over 12 hours
         old. A laptop should not have to be awake at 03:15. -->
    <key>RunAtLoad</key>
    <true/>
    <key>StartInterval</key>
    <integer>21600</integer>

    <!-- NOT inside iCloud Drive. launchd cannot open a log file there and
         refuses to start the job at all (EX_CONFIG, exit 78) - it looks
         installed and does nothing. Backups live in iCloud; logs do not. -->
    <key>StandardOutPath</key>
    <string>$LOGFILE</string>
    <key>StandardErrorPath</key>
    <string>$LOGFILE</string>
</dict>
</plist>
PLIST_END

echo "restarting the job"
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"

echo
echo "installed one job: at login, then every 6 hours while the Mac is on."
echo "backups: ${PREPEAT_BACKUP_DIR:-$HOME/Prepeat-backups}"
echo "log:     $LOGFILE"
echo "run now:  npm run backup"
