#!/usr/bin/env bash
#
# Installs the nightly backup job.  Run: npm run backup:install
#
# Why an installer rather than just pointing launchd at the repo: ~/Documents
# is a macOS privacy-protected folder and a launchd job cannot read from it.
# The first scheduled run died with "Operation not permitted" (exit 126) even
# though the identical script worked when run by hand, because a Terminal has
# permissions a background job does not. So the runtime copy lives in
# ~/Library/Application Support/Prepeat, which is not protected.
#
# The repo stays the source of truth. Re-run this after editing
# scripts/backup-supabase.sh, or the job keeps running the old version.

set -euo pipefail

LABEL="dk.sebell.prepeat.backup"
CHECK_LABEL="dk.sebell.prepeat.backup-check"
RUNTIME="$HOME/Library/Application Support/Prepeat"
AGENTS="$HOME/Library/LaunchAgents"
PLIST="$AGENTS/$LABEL.plist"
CHECK_PLIST="$AGENTS/$CHECK_LABEL.plist"
SCRIPTS="$(cd "$(dirname "$0")" && pwd)"
SRC="$SCRIPTS/backup-supabase.sh"
CHECK_SRC="$SCRIPTS/check-backup-freshness.sh"
LOGDIR="${PREPEAT_BACKUP_DIR:-$HOME/Prepeat-backups}"

[ -f "$SRC" ] || { echo "cannot find $SRC" >&2; exit 1; }
[ -f "$CHECK_SRC" ] || { echo "cannot find $CHECK_SRC" >&2; exit 1; }

echo "installing runtime copies -> $RUNTIME"
mkdir -p "$RUNTIME" "$AGENTS" "$LOGDIR"
cp "$SRC" "$RUNTIME/backup-supabase.sh"
cp "$CHECK_SRC" "$RUNTIME/check-backup-freshness.sh"
chmod 700 "$RUNTIME/backup-supabase.sh" "$RUNTIME/check-backup-freshness.sh"

echo "writing $PLIST"
cat > "$PLIST" <<PLIST_END
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- GENERATED by scripts/install-backup-job.sh - do not edit by hand. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$RUNTIME/backup-supabase.sh</string>
    </array>

    <key>WorkingDirectory</key>
    <string>$RUNTIME</string>

    <!-- Only psql and curl are needed; nothing from the repo, and no node. -->
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>

    <!-- 03:15 nightly. If the Mac is asleep at that hour launchd runs the job
         once on the next wake, so a closed lid delays it, never skips it. -->
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>3</integer>
        <key>Minute</key>
        <integer>15</integer>
    </dict>

    <key>StandardOutPath</key>
    <string>$LOGDIR/backup.log</string>
    <key>StandardErrorPath</key>
    <string>$LOGDIR/backup.log</string>

    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
PLIST_END

echo "writing $CHECK_PLIST"
cat > "$CHECK_PLIST" <<PLIST_END
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- GENERATED by scripts/install-backup-job.sh - do not edit by hand. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$CHECK_LABEL</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$RUNTIME/check-backup-freshness.sh</string>
    </array>

    <key>WorkingDirectory</key>
    <string>$RUNTIME</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>

    <!-- RunAtLoad is the point of this job: it fires when Thomas logs in, so a
         fortnight away with the Mac shut is caught the moment he comes back.
         The 10:00 run covers a Mac that simply stays logged in. -->
    <key>RunAtLoad</key>
    <true/>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>10</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>

    <key>StandardOutPath</key>
    <string>$LOGDIR/backup.log</string>
    <key>StandardErrorPath</key>
    <string>$LOGDIR/backup.log</string>
</dict>
</plist>
PLIST_END

echo "restarting the jobs"
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"
launchctl bootout "gui/$(id -u)/$CHECK_LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$CHECK_PLIST"

echo
echo "installed two jobs:"
echo "  backup       03:15 nightly"
echo "  freshness    at login, and 10:00 daily - warns if backups go stale"
echo
echo "run them now with:"
echo "  launchctl kickstart -k gui/$(id -u)/$LABEL"
echo "  launchctl kickstart -k gui/$(id -u)/$CHECK_LABEL"
echo "watch the log at:  $LOGDIR/backup.log"
